apiVersion: v1
kind: Secret
metadata:
  name: secret-demo-ckad
type: Opaque
data:
  username: dXNlcm5hbWU=  # "username" en Base64
  password: cGFzc3dvcmQ=  # "password" en Base64
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-demo-pod
spec:
  containers:
  - name: busybox
    image: busybox
    env:
    - name: USERNAME
      valueFrom:
        secretKeyRef:
          name: secret-demo-ckad
          key: username
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: secret-demo-ckad
          key: password
    command: [ "sh", "-c", "echo Username: $USERNAME , echo Password: $PASSWORD && sleep 3600" ]