apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mitocodes.ckad.example.com
spec:
  group: ckad.example.com
  scope: Namespaced
  names:
    plural: mitocodes
    singular: mitocode
    kind: Mitocode
    shortNames:
      - mc
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                pais:
                  type: string
                nombre:
                  type: string