apiVersion: v1
kind: LimitRange
metadata:
  name: mem-cpu-limit-range
  namespace: dev-environment
spec:
  limits:
  - max:
      memory: "1Gi"
      cpu: "1"
    min:
      memory: "256Mi"
      cpu: "0.1"
    default:
      memory: "512Mi"
      cpu: "0.5"
    defaultRequest:
      memory: "256Mi"
      cpu: "0.2"
    type: Container