apiVersion: v1
kind: Pod
metadata:
  name: affinity-minikube
spec:
  containers:
  - name: affinity-minikube
    image: httpd
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: disk
            operator: In
            values:
            - ssd