apiVersion: v1
kind: Pod
metadata:
  name: request-limit
spec:
  containers:
  - name: request-limit
    image: nginx
    resources:
      requests:
        memory: "100Mi"
        cpu: "100m"
      limits:
        memory: "500Mi"
        cpu: "300m"