apiVersion: v1
kind: Pod
metadata:
  name: tolerations-minikube
spec:
  tolerations:
  - key: provider
    value: azure
    operator: Equal
    effect: NoSchedule
  containers:
  - name: tolerations-pod
    image: nginx