apiVersion: apps/v1
kind: Deployment
metadata:
  name:  app-web
  labels:
    app:  web
spec:
  selector:
    matchLabels:
      app: web
  replicas: 1
  template:
    metadata:
      labels:
        app:  web
    spec:
      containers:
      - name:  web
        image:  httpd
        ports:
        - containerPort:  80