apiVersion: v1
kind: Pod
metadata:
  name: cfgmap-pod
spec:
  containers:
  - name: app-container
    image: busybox
    command: ["/bin/sh", "-c", "env && sleep 3600"]
    envFrom:
    - configMapRef:
        name: app-config