apiVersion: v1
kind: Pod
metadata:
  name: multi-volume-pod
spec:
  containers:
    - name: app-container
      image: busybox
      command: ["/bin/sh", "-c", "while true; do echo $(date) >> /data/logs/app.log; sleep 50; done"]
      volumeMounts:
        - name: temp-storage
          mountPath: /data/temp
        - name: log-storage
          mountPath: /data/logs
  volumes:
    - name: temp-storage
      emptyDir: {}
    - name: log-storage
      hostPath:
        path: /var/log/k8s-app
        type: DirectoryOrCreate