apiVersion: v1
kind: Pod
metadata:
  name: logger
spec:
  containers:
    - name: apache-container
      image: httpd
      volumeMounts:
        - name: log-volume
          mountPath: /usr/local/apache2/logs
  volumes:
    - name: log-volume
      hostPath:
        path: /var/log/httpd
        type: DirectoryOrCreate