apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeport-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodeport-app
  template:
    metadata:
      labels:
        app: nodeport-app
    spec:
      containers:
      - name: httpd
        image: httpd
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nodeport-app-service
spec:
  type: NodePort
  selector:
    app: nodeport-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080