apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-dns-access
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: dns-access
  egress:
  - to:
    - ipBlock:
        cidr: 8.8.8.8/32
  policyTypes:
  - Egress
---
apiVersion: v1
kind: Pod
metadata:
  name: allowed-pod
  labels:
    app: dns-access
spec:
  containers:
  - name: curl
    image: curlimages/curl
    command: ["sleep", "3600"]