apiVersion: v1
kind: Pod
metadata:
  name: multi-ckad
spec:
  containers:
  - name: web
    image: httpd:latest
    ports:
    - containerPort: 80
  - name: batch
    image: busybox
    command: ["/bin/sh", "-c", "echo 'Segundo container' && sleep 3600"]