apiVersion: v1
kind: Pod
metadata:
  name: reader-pod
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sh", "-c", "cat /data/mensaje.txt && sleep 3600"]
      volumeMounts:
        - mountPath: "/data"
          name: storage
  volumes:
    - name: storage
      persistentVolumeClaim:
        claimName: my-pvc