apiVersion: v1
kind: Pod
metadata:
  name: multi-container-ckad
spec:
  containers:
  - name: app-ckad
    image: busybox
    command: ["sh", "-c", "echo 'Estoy dando el examen ckad!!' > /shared/message && sleep 3600"]
    volumeMounts:
    - name: shared-data
      mountPath: /shared
  - name: second-ckad
    image: busybox
    command: ["sh", "-c", "cat /shared/message && sleep 3600"]
    volumeMounts:
    - name: shared-data
      mountPath: /shared
  volumes:
  - name: shared-data
    emptyDir: {}