apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-namespace
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: db-app
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: trusted
  policyTypes:
  - Ingress
---
apiVersion: v1
kind: Pod
metadata:
  name: db-app
  namespace: default
  labels:
    app: db-app
spec:
  containers:
  - name: db
    image: nginx
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-other-namespace
  namespace: trusted
spec:
  containers:
  - name: pod-other
    image: curlimages/curl
    command: [ "sleep", "3600" ]