apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: prueba
  name: prueba
spec:
  containers:
  - image: nginx
    name: prueba
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
