apiVersion: v1
kind: ServiceAccount
metadata:
  name: reader-ckad
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-reader-binding
  namespace: default 
subjects:
- kind: ServiceAccount
  name: reader-ckad
  namespace: default
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
  namespace: default
spec:
  serviceAccountName: reader-ckad
  containers:
  - name: kubectl
    image: bitnami/kubectl:latest
    command:
    - sleep
    - "3600"