apiVersion: apps/v1
kind: Deployment
metadata:
  name:  deployment-demo
  labels:
    empresa: mitocode
spec:
  selector:
    matchLabels:
      app: demo
  replicas: 2
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo
        image: nginx
        ports:
        - containerPort:  80
          name: demo
      restartPolicy: Always
