apiVersion: v1
kind: Pod
metadata:
  name: limit-prueba
  namespace: dev-environment
spec:
  containers:
  - name: limit-prueba
    resources:
      requests:
        memory: "100Mi"
        cpu: "100m"
      limits:
        memory: "2Gi"
        cpu: "2"
    image: nginx:alpine
    ports:
    - containerPort:  80
      name:  http