apiVersion: v1
kind: Pod
metadata:
  name: pregunta2
spec:
  tolerations:
  - key: "key1"
    operator: "Exists"
    effect: "NoSchedule"
  containers:
  - name: pregunta2
    image: redis
    ports:
    - containerPort:  80
      name:  http