apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
data:
  config_key: "3"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crash-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: busybox
        command: ["/bin/sh", "-c", "echo 'Starting App'; sleep 5; echo $CONFIG_VAR"]
        env:
        - name: CONFIG_VAR
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: config_key