apiVersion: v1
kind: Pod
metadata:
  name: my-app
spec:
  containers:
  - name: app
    image: busybox
    command: ["/bin/sh", "-c", "echo $MY_VAR && sleep 10"]
    env:
    - name: MY_VAR
      value: CKAD