apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: old-ingress
spec:
  rules:
  - host: example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: my-service
          servicePort: 80