apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: new-ingress
spec:
  rules:
  - host: example.com
    http:
      paths:
      - path: /
        pathType: Prefix  # Requerido en la nueva versión
        backend:
          service: # Nueva estructura
            name: my-service
            port:
              number: 80